In [15]:
from sklearn import datasets
from sklearn.cluster import KMeans
import sklearn.metrics as sm
import pandas as pd
import numpy as np

In [16]:
iris=datasets.load_iris()
X=iris.data
y=iris.target

In [24]:
model=KMeans(n_clusters=3)
model.fit(X)
print('The accuracy score of K-Mean:',int(sm.accuracy_score(y,model.labels_)*100),'%')
print('The Confusion matrix of K-Mean:',sm.confusion_matrix(y,model.labels_))

The accuracy score of K-Mean: 24 %
The Confusion matrix of K-Mean: [[ 0 50  0]
 [48  0  2]
 [14  0 36]]


In [25]:
from sklearn import preprocessing
scaler=preprocessing.StandardScaler()
scaler.fit(X)
xs=scaler.transform(X)


In [26]:
from sklearn.mixture import GaussianMixture
gmm=GaussianMixture(n_components=3)
gmm.fit(xs)
y_gmm=gmm.predict(xs)
print('The accuracy score of EM:',int(sm.accuracy_score(y,y_gmm)*100),'%')
print('The confusion matrix of EM:',sm.confusion_matrix(y,y_gmm))

The accuracy score of EM: 33 %
The confusion matrix of EM: [[ 0 50  0]
 [45  0  5]
 [ 0  0 50]]
